import java.io.*;
import javax.swing.JOptionPane;
import java.util.*;
public class Transfer extends javax.swing.JFrame {

    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AccNumTF = new javax.swing.JTextField();
        AmountTF = new javax.swing.JTextField();
        TransferFundsButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transfer to Account Number:");

        jLabel2.setText("Amount");

        TransferFundsButton.setText("Transfer funds");
        TransferFundsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferFundsButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Go back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccNumTF)
                    .addComponent(AmountTF, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(TransferFundsButton)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(AccNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(AmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(TransferFundsButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransferFundsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferFundsButtonActionPerformed
        User u = AccountPIN.user;
        int accNum = u.getAccNum(), PIN = u.getPIN(), balance = u.viewBalance();
        long phoneNumber = u.getPhoneNumber();
        MiniStatement ms = Menu.ms;
        
        int transferToAccNum = 0, amount = 0;
        //To check whether the account number entered is an integer or not
        try {
            transferToAccNum = Integer.parseInt(AccNumTF.getText());
            amount = Integer.parseInt(AmountTF.getText());
            
            if (balance < amount) {
                JOptionPane.showMessageDialog(this, "Not enough funds in account!");
                AccNumTF.setText("");
                AmountTF.setText("");
            }
            else if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid amount");
                AccNumTF.setText("");
                AmountTF.setText("");
            }
            else {
                String csvFile = "Users.csv";
                String tempFile = "temp.csv";
                File oldFile = new File(csvFile);
                File newFile = new File(tempFile);
                String fileAccNum ="", filePIN = "", fileBalance = "", filePhoneNumber = "";

                //To check whether the given transfer to account number exists or not if exists then make appropriate changes
                try {               
                    Scanner obj = new Scanner(new File(csvFile));
                    obj.useDelimiter("[,\n]");

                    int flag = 0;
                    while (obj.hasNext()) {
                        fileAccNum = obj.next();
                        filePIN = obj.next();
                        fileBalance = obj.next();
                        filePhoneNumber = obj.next();
                        filePhoneNumber = filePhoneNumber.replace("\r", "");
                        if (transferToAccNum == Integer.parseInt(fileAccNum)) {
                            flag = 1;
                            break;
                        }
                    }
                    obj.close();
                    if (flag == 1) {    //That is the given record exists then we make the changes

                        u.setBalance(balance-amount);
                        ms.changetransferFunds(transferToAccNum, amount);

                        //Changing CSV Values 
                        /*A temporary file is created in which the data is copied from the Users.csv file but where
                        the changes in the user's balance and transferred account number's balance is changed accordingly. Then the Users.csv file is deleted and
                        the temp.csv file is renamed as Users.csv*/
                        //https://www.youtube.com/watch?v=TpyRKom0X_s video was referred 


                        try {
                            FileWriter fw = new FileWriter(tempFile, true);
                            BufferedWriter bw = new BufferedWriter(fw);
                            PrintWriter pw = new PrintWriter(bw);

                            Scanner sc = new Scanner(new File(csvFile));
                            sc.useDelimiter("[,\n]");

                            while (sc.hasNext()) {
                                fileAccNum = sc.next();
                                filePIN = sc.next();
                                fileBalance = sc.next();
                                filePhoneNumber = sc.next();
                                filePhoneNumber = filePhoneNumber.replace("\r", "");

                                if (Integer.parseInt(fileAccNum) == transferToAccNum) {
                                    pw.println(fileAccNum+","+filePIN+","+(Integer.parseInt(fileBalance) + amount) + "," + filePhoneNumber); //Added amount to transfer account
                                }
                                else if (Integer.parseInt(fileAccNum)==accNum) {
                                    pw.println(u.getAccNum()+","+u.getPIN()+","+u.viewBalance()+","+u.getPhoneNumber());
                                }
                                else {
                                    pw.println(fileAccNum + "," + filePIN + "," + fileBalance + "," + filePhoneNumber);
                                }
                            }
                            sc.close();
                            pw.flush();
                            pw.close();
                            oldFile.delete();
                            File dump = new File(csvFile);
                            newFile.renameTo(dump);
                            JOptionPane.showMessageDialog(this, "Funds transferred successfully");
                        }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "There was an error: "+e);
                            e.printStackTrace();
                        }
                   }
                    else if (flag == 0) {
                        JOptionPane.showMessageDialog(this, "The given account number does not exist");
                        AccNumTF.setText("");
                        AmountTF.setText("");
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "There was an error: "+e);
                    e.printStackTrace();
                }

            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter an integer");
            AccNumTF.setText("");
            AmountTF.setText("");
        }
    }//GEN-LAST:event_TransferFundsButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNumTF;
    private javax.swing.JTextField AmountTF;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton TransferFundsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
